site_name: Serverseitige Softwareentwicklung
site_description: Skriptum zur Lehrveranstaltung Serverseitige Softwareentwicklung
site_author: Stefan Huber

repo_url: https://github.com/stefanhuber/Serverseitige-Softwareentwicklung
edit_uri: https://github.com/stefanhuber/Serverseitige-Softwareentwicklung

nav:
  - Home: 'index.md'
  - 'PHP':
    - 'Grundlagen': 'php/grundlagen.md'
    - 'Arrays': 'php/arrays.md'    
    - 'Funktionen': 'php/funktionen.md'    
    - 'OOP': 'php/objektorientierte-programmierung.md'
    - 'Superglobals': 'php/superglobals.md'
    - 'Sessions und Cookies': 'php/sessions-und-cookies.md'
    - 'Errors und Exceptions': 'php/errors-und-exceptions.md'
    - 'Datenbanken': 'php/datenbanken.md'
    - 'Quellcode organisieren': 'php/quellcode-organisieren.md'
    - 'Arbeiten mit Projektabhängigkeiten':  'php/arbeiten-mit-projektabhaengigkeiten.md'
  - 'Regex':
    - 'Einführung': 'regex/einführung.md'
    - 'Zeichenklassen': 'regex/zeichenklassen.md'
    - 'Wiederholungen': 'regex/wiederholungen.md'
    - 'Gruppierungen': 'regex/gruppierungen.md'
    - 'Alternative': 'regex/alternative.md'
    - 'Anker und Wortgrenzen': 'regex/anker-und-wortgrenzen.md'
    - 'Modifikationen': 'regex/modifikationen.md'
    - 'Beispiele': 'regex/beispiele.md'
    - 'Nutzung mit PHP': 'regex/nutzung-mit-php.md'
  - 'Web-Server':
    - 'Einführung': 'webserver/einführung.md'
    - 'Wichtige Funktionen': 'webserver/funktionen.md'
    - 'Nginx Nutzung': 'webserver/nginx-nutzung.md'
    - 'Nginx Konfiguration': 'webserver/nginx-konfiguration.md'
    - 'WebSockets': 'webserver/websockets.md'
  - 'Tutorials':
    - 'PHP Installation': 'tutorials/01.md'
    - 'PHP Webserver': 'tutorials/02.md'
    - 'PHP Konfiguration': 'tutorials/03.md'
    - 'Arbeiten mit SQLite': 'tutorials/04.md'  
    - 'Übungsblatt 1 - Übung 0': 'tutorials/05.md'

theme:
  name: material
  language: de
  features:
    - navigation.tabs
  icon:
    logo: fontawesome/solid/server

copyright: 'CC-BY-SA / Stefan Huber'

docs_dir: content
site_dir: docs

extra:
  search:
    language: de

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search:
      lang: de
  