site_name: Serverseitige Softwareentwicklung
site_description: Skriptum zur Lehrveranstaltung Serverseitige Softwareentwicklung
site_author: Stefan Huber

repo_url: https://github.com/stefanhuber/Serverseitige-Softwareentwicklung
edit_uri: https://github.com/stefanhuber/Serverseitige-Softwareentwicklung

nav:
  - Home: 'index.md'
  - 'PHP':
    - 'Grundlagen': 'php/01.md'
    - 'Arrays': 'php/02.md'
    - 'Superglobals': 'php/03.md'
    - 'Funktionen': 'php/04.md'
    - 'OOP': 'php/05.md'
    - 'Sessions und Cookies': 'php/06.md'
    - 'Errors und Exceptions': 'php/07.md'
    - 'Datenbanken': 'php/08.md'
    - 'Quellcode einbinden': 'php/09.md'
    - 'Arbeiten mit Projektabhängigkeiten':  'php/10.md'
  - 'Regex':
    - 'Einführung': 'regex/einführung.md'
    - 'Zeichenklassen': 'regex/zeichenklassen.md'
    - 'Wiederholungen': 'regex/wiederholungen.md'
    - 'Gruppierungen': 'regex/gruppierungen.md'
    - 'Alternative': 'regex/alternative.md'
    - 'Anker und Wortgrenzen': 'regex/anker-und-wortgrenzen.md'
    - 'Modifikationen': 'regex/modifikationen.md'
    - 'Beispiele': 'regex/beispiele.md'
    - 'Nutzung mit PHP': 'regex/nutzung-mit-php.md'
  - 'Web-Server':
    - 'Einführung': 'webserver/einführung.md'
    - 'Wichtige Funktionen': 'webserver/funktionen.md'
    - 'Nginx Nutzung': 'webserver/nginx-nutzung.md'
    - 'Nginx Konfiguration': 'webserver/nginx-konfiguration.md'
    - 'WebSockets': 'webserver/websockets.md'
  - 'Tutorials':
    - 'PHP Installation': 'tutorials/01.md'
    - 'PHP Webserver': 'tutorials/02.md'
    - 'PHP Konfiguration': 'tutorials/03.md'
    - 'Arbeiten mit SQLite': 'tutorials/04.md'  
  - 'Übungstutorials':
    - 'Übungsblatt 1 - Übung 0': 'exercises/01.md'

theme:
  name: material
  language: de
  features:
    - tabs
  icon:
    logo: fontawesome/solid/server

copyright: 'CC-BY-SA / Stefan Huber'

docs_dir: content
site_dir: docs

extra:
  search:
    language: de

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false

plugins:
  - search
  - minify:
      minify_html: true
  